T-feature:
  - '/^feat(\(.+\))?!?:/i'

T-fix:
  - '/^fix(\(.+\))?!?:/i'

T-refactor:
  - '/^refactor(\(.+\))?!?:/i'

T-perf:
  - '/^perf(\(.+\))?!?:/i'

T-test:
  - '/^test(\(.+\))?!?:/i'

T-chore:
  - '/^chore(\(.+\))?!?:/i'
