use-grammars = { except = [ "gotmpl" ] }

[language-server.gnopls]
command = "gnopls"

[[language]]
comment-token    = "//"
file-types       = ["gno"]
indent           = { tab-width = 4, unit = "  " }
injection-regex  = "gno"
language-servers = ["gnopls"]
name             = "gno"
formatter        = { command = "gofumpt" }
auto-format      = true
roots            = ["gnowork.toml", "gnomod.toml"]
scope            = "source.gno"
shebangs         = []

[[grammar]]
name   = "gno"
source = { git = "https://github.com/unionlabs/tree-sitter-gno", rev = "e0549d4dd8b5d02184ffacbb5481e93f41abbbdb" }
