module = "gno.land/r/onbloc/ibc/lightclients/state_lens/ics23_mpt"
gno = "0.9"

[require]
"gno.land/p/onbloc/encoding/abi" = "v0.0.0"
"gno.land/p/onbloc/encoding/rlp" = "v0.0.0"
"gno.land/p/onbloc/ibc/union/lightclient/state_lens/ics23_mpt" = "v0.0.0"
"gno.land/p/onbloc/ibc/union/types" = "v0.0.0"
"gno.land/p/onbloc/verifier/evm/storage" = "v0.0.0"
"gno.land/r/onbloc/ibc/union/core" = "v0.0.0"
