//! Emit ground-truth Solidity ABI encodings for every ZKGM struct + scenario.
//!
//! The struct definitions below are a verbatim copy of
//! `union/cosmwasm/app/ucs03-zkgm/src/com.rs` (the `sol!` block). Keeping them
//! in sync is the whole point of this tool — if Union ever changes the wire
//! format, the test vectors regenerate against the new shape and the gno
//! decoder's tests reveal the drift.
//!
//! Output: a JSON array of `Vector` records on stdout, each containing the
//! struct's logical fields (decoded form) and the canonical ABI hex
//! (encoded form). The gno tests load this file from
//! `gno.land/p/aib/encoding/abi/testdata/vectors.json`, build the same Gno
//! struct from `fields`, encode it, and assert byte equality with `abi_hex`.
//! The decoder path runs the inverse.
//!
//! Regenerate with `make refresh-abi-vectors` from the repo root.

use std::str::FromStr;

use alloy_primitives::{Bytes, FixedBytes, U256};
use alloy_sol_types::{abi::TokenSeq, sol, SolType, SolValue};
use serde::Serialize;
use serde_json::{json, Value};

sol! {
    #[derive(Debug)]
    struct ZkgmPacket {
        bytes32 salt;
        uint256 path;
        Instruction instruction;
    }

    #[derive(Debug)]
    struct Instruction {
        uint8 version;
        uint8 opcode;
        bytes operand;
    }

    struct Forward {
        uint256 path;
        // TODO: Forward v2 to remove this field
        uint64 timeout_height;
        uint64 timeout_timestamp;
        Instruction instruction;
    }

    struct Call {
        bytes sender;
        bool eureka;
        bytes contract_address;
        bytes contract_calldata;
    }

    struct Batch {
        Instruction[] instructions;
    }

    #[derive(Debug, PartialEq)]
    struct TokenOrderV1 {
        bytes sender;
        bytes receiver;
        bytes base_token;
        uint256 base_amount;
        string base_token_symbol;
        string base_token_name;
        uint8 base_token_decimals;
        uint256 base_token_path;
        bytes quote_token;
        uint256 quote_amount;
    }

    #[derive(Debug, PartialEq)]
    struct TokenOrderV2 {
        bytes sender;
        bytes receiver;
        bytes base_token;
        uint256 base_amount;
        bytes quote_token;
        uint256 quote_amount;
        uint8 kind;
        bytes metadata;
    }

    #[derive(Debug, PartialEq)]
    struct TokenMetadata {
        bytes implementation;
        bytes initializer;
    }

    #[derive(Debug, PartialEq)]
    struct SolverMetadata {
        bytes solverAddress;
        bytes metadata;
    }

    #[derive(Debug)]
    struct Ack {
        uint256 tag;
        bytes inner_ack;
    }

    struct BatchAck {
        bytes[] acknowledgements;
    }

    #[derive(Debug)]
    struct TokenOrderAck {
        uint256 fill_type;
        bytes market_maker;
    }
}

#[derive(Serialize)]
struct Vector {
    /// Stable, human-readable identifier used by the gno test runner.
    name: String,
    /// One of the struct names defined above (e.g. "Instruction", "ZkgmPacket").
    /// The gno test dispatches on this to pick which struct to construct.
    #[serde(rename = "type")]
    ty: String,
    /// Logical struct field values. Schema follows the per-type conventions
    /// documented in README.md. Used to drive both the encoder test (build
    /// from these fields, expect `abi_hex`) and the decoder test (decode
    /// `abi_hex`, expect these fields). When `null`, the gno test skips the
    /// encoder check and runs decode-only assertions on `abi_hex`.
    fields: Value,
    /// Canonical Solidity ABI encoding produced by `alloy_sol_types`, with
    /// `0x` prefix.
    abi_hex: String,
}

fn hex0x(bytes: &[u8]) -> String {
    format!("0x{}", hex::encode(bytes))
}

// Union encodes ZKGM wire bytes via `abi_encode_params` / decodes via
// `abi_decode_params_validate` — see contract.rs:270, 556, 578, etc. The
// "_params" flavor treats a struct's fields as the top-level tuple (no
// extra `head_offset(0x20)` prefix that plain `abi_encode` adds for a
// dynamic top-level value). Every gno encoder/decoder in this repo MUST
// match this flavor; the test vectors below are produced with it.
//
// The where-clause repeats SolValue::abi_encode_params's own bound: the
// Token type associated with the SolType must implement TokenSeq, which
// is true for tuples and struct-tuples generated by `sol!`.
fn vector<T>(name: &str, ty: &str, fields: Value, value: &T) -> Vector
where
    T: SolValue,
    for<'a> <<T as SolValue>::SolType as SolType>::Token<'a>: TokenSeq<'a>,
{
    Vector {
        name: name.to_string(),
        ty: ty.to_string(),
        fields,
        abi_hex: hex0x(&value.abi_encode_params()),
    }
}

fn fixed32(fill: u8) -> FixedBytes<32> {
    FixedBytes::from([fill; 32])
}

fn vectors() -> Vec<Vector> {
    let mut out = Vec::new();

    // ────────────────────────────────────────────────────────────────────
    // Instruction
    // ────────────────────────────────────────────────────────────────────
    {
        let v = Instruction {
            version: 0x00,
            opcode: 0x01,
            operand: Bytes::new(),
        };
        out.push(vector(
            "Instruction_empty_operand",
            "Instruction",
            json!({ "version": 0, "opcode": 1, "operand": "0x" }),
            &v,
        ));
    }
    {
        let v = Instruction {
            version: 0x02,
            opcode: 0x03,
            operand: Bytes::from(vec![0xAA, 0xBB, 0xCC]),
        };
        out.push(vector(
            "Instruction_short_operand",
            "Instruction",
            json!({ "version": 2, "opcode": 3, "operand": "0xaabbcc" }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Call
    // ────────────────────────────────────────────────────────────────────
    {
        let v = Call {
            sender: Bytes::from(b"alice".to_vec()),
            eureka: true,
            contract_address: Bytes::from(b"bobcontract".to_vec()),
            contract_calldata: Bytes::from(vec![0xCA, 0xFE]),
        };
        out.push(vector(
            "Call_basic",
            "Call",
            json!({
                "sender": hex0x(b"alice"),
                "eureka": true,
                "contract_address": hex0x(b"bobcontract"),
                "contract_calldata": "0xcafe",
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // TokenOrderV2
    // ────────────────────────────────────────────────────────────────────
    {
        let v = TokenOrderV2 {
            sender: Bytes::from(b"alice".to_vec()),
            receiver: Bytes::from(b"bob".to_vec()),
            base_token: Bytes::from(b"unionToken".to_vec()),
            base_amount: U256::from(1_000_000u64),
            quote_token: Bytes::from(b"uatom".to_vec()),
            quote_amount: U256::from(2_500_000u64),
            kind: 0x01, // ESCROW
            metadata: Bytes::new(),
        };
        out.push(vector(
            "TokenOrderV2_escrow_basic",
            "TokenOrderV2",
            json!({
                "sender": hex0x(b"alice"),
                "receiver": hex0x(b"bob"),
                "base_token": hex0x(b"unionToken"),
                "base_amount": "1000000",
                "quote_token": hex0x(b"uatom"),
                "quote_amount": "2500000",
                "kind": 1,
                "metadata": "0x",
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // ZkgmPacket — outer envelope (recursively contains Instruction)
    // ────────────────────────────────────────────────────────────────────
    {
        let inner = Instruction {
            version: 0x00,
            opcode: 0x01,
            operand: Bytes::from(vec![0x01, 0x02]),
        };
        let v = ZkgmPacket {
            salt: fixed32(0xAB),
            path: U256::from(7u64),
            instruction: inner,
        };
        out.push(vector(
            "ZkgmPacket_with_short_call_operand",
            "ZkgmPacket",
            json!({
                "salt": hex0x(&[0xAB; 32]),
                "path": "7",
                "instruction": {
                    "version": 0,
                    "opcode": 1,
                    "operand": "0x0102",
                },
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Bytes-length boundaries (drive 32-byte alignment paths in the codec)
    // ────────────────────────────────────────────────────────────────────
    for &len in &[0usize, 31, 32, 33, 64] {
        let sender: Vec<u8> = (0..len).map(|i| ((i + 1) & 0xff) as u8).collect();
        let v = Call {
            sender: Bytes::from(sender.clone()),
            eureka: false,
            contract_address: Bytes::from(b"target".to_vec()),
            contract_calldata: Bytes::new(),
        };
        out.push(vector(
            &format!("Call_sender_len{}", len),
            "Call",
            json!({
                "sender": hex0x(&sender),
                "eureka": false,
                "contract_address": hex0x(b"target"),
                "contract_calldata": "0x",
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Forward (single hop + recursive 3 hops)
    // ────────────────────────────────────────────────────────────────────
    {
        // Forward → Call
        let inner_call = Call {
            sender: Bytes::from(b"sender".to_vec()),
            eureka: true,
            contract_address: Bytes::from(b"contract".to_vec()),
            contract_calldata: Bytes::from(vec![0xCA, 0xFE]),
        };
        let inner_call_hex = hex0x(&inner_call.abi_encode_params());
        let v = Forward {
            path: U256::from(0x12345u64),
            timeout_height: 100,
            timeout_timestamp: 1_700_000_000_000_000_000,
            instruction: Instruction {
                version: 0x00,
                opcode: 0x01, // OP_CALL
                operand: Bytes::from(inner_call.abi_encode_params()),
            },
        };
        out.push(vector(
            "Forward_with_call",
            "Forward",
            json!({
                "path": "74565",  // 0x12345
                "timeout_height": 100,
                "timeout_timestamp": "1700000000000000000",
                "instruction": {
                    "version": 0,
                    "opcode": 1,
                    "operand": inner_call_hex,
                },
            }),
            &v,
        ));
    }
    {
        // Forward → Forward → Call (3 hops)
        let leaf_call = Call {
            sender: Bytes::from(b"alice".to_vec()),
            eureka: false,
            contract_address: Bytes::from(b"final-target".to_vec()),
            contract_calldata: Bytes::from(vec![0xDE, 0xAD]),
        };
        let _leaf_call_hex = hex0x(&leaf_call.abi_encode_params());
        let mid_forward = Forward {
            path: U256::from(2u64),
            timeout_height: 0,
            timeout_timestamp: 1_800_000_000_000_000_000,
            instruction: Instruction {
                version: 0,
                opcode: 0x01, // OP_CALL
                operand: Bytes::from(leaf_call.abi_encode_params()),
            },
        };
        let mid_forward_hex = hex0x(&mid_forward.abi_encode_params());
        let v = Forward {
            path: U256::from(1u64),
            timeout_height: 0,
            timeout_timestamp: 1_800_000_000_000_000_000,
            instruction: Instruction {
                version: 0,
                opcode: 0x00, // OP_FORWARD
                operand: Bytes::from(mid_forward.abi_encode_params()),
            },
        };
        // The operand of the outer Forward.instruction is itself an encoded
        // Forward (whose own .instruction.operand is an encoded Call). The
        // gno decoder reaches the leaf by feeding `operand` back through the
        // codec recursively — see the "operand" hex below for the mid-Forward
        // bytes.
        out.push(vector(
            "Forward_recursive_two_hops",
            "Forward",
            json!({
                "path": "1",
                "timeout_height": 0,
                "timeout_timestamp": "1800000000000000000",
                "instruction": {
                    "version": 0,
                    "opcode": 0,
                    "operand": mid_forward_hex,
                },
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Batch (empty / single / three)
    // ────────────────────────────────────────────────────────────────────
    {
        let v = Batch {
            instructions: vec![],
        };
        out.push(vector(
            "Batch_empty",
            "Batch",
            json!({ "instructions": [] }),
            &v,
        ));
    }
    {
        let only = Instruction {
            version: 0,
            opcode: 0x01,
            operand: Bytes::from(vec![0x11]),
        };
        let v = Batch {
            instructions: vec![only],
        };
        out.push(vector(
            "Batch_single",
            "Batch",
            json!({
                "instructions": [
                    { "version": 0, "opcode": 1, "operand": "0x11" },
                ],
            }),
            &v,
        ));
    }
    {
        let v = Batch {
            instructions: vec![
                Instruction { version: 0, opcode: 0x01, operand: Bytes::from(vec![0xA1]) },
                Instruction { version: 1, opcode: 0x03, operand: Bytes::from(vec![0xA2, 0xA2]) },
                Instruction { version: 2, opcode: 0x01, operand: Bytes::new() },
            ],
        };
        out.push(vector(
            "Batch_three",
            "Batch",
            json!({
                "instructions": [
                    { "version": 0, "opcode": 1, "operand": "0xa1" },
                    { "version": 1, "opcode": 3, "operand": "0xa2a2" },
                    { "version": 2, "opcode": 1, "operand": "0x" },
                ],
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // TokenOrderV1 (legacy form)
    // ────────────────────────────────────────────────────────────────────
    {
        let v = TokenOrderV1 {
            sender: Bytes::from(b"alice".to_vec()),
            receiver: Bytes::from(b"bob".to_vec()),
            base_token: Bytes::from(b"unionToken".to_vec()),
            base_amount: U256::from(1_000u64),
            base_token_symbol: "UNI".to_string(),
            base_token_name: "Union Token".to_string(),
            base_token_decimals: 18,
            base_token_path: U256::from(42u64),
            quote_token: Bytes::from(b"uatom".to_vec()),
            quote_amount: U256::from(2_000u64),
        };
        out.push(vector(
            "TokenOrderV1_basic",
            "TokenOrderV1",
            json!({
                "sender": hex0x(b"alice"),
                "receiver": hex0x(b"bob"),
                "base_token": hex0x(b"unionToken"),
                "base_amount": "1000",
                "base_token_symbol": "UNI",
                "base_token_name": "Union Token",
                "base_token_decimals": 18,
                "base_token_path": "42",
                "quote_token": hex0x(b"uatom"),
                "quote_amount": "2000",
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Ack (failure / success with payload)
    // ────────────────────────────────────────────────────────────────────
    {
        let v = Ack {
            tag: U256::ZERO,
            inner_ack: Bytes::new(),
        };
        out.push(vector(
            "Ack_failure",
            "Ack",
            json!({ "tag": "0", "inner_ack": "0x" }),
            &v,
        ));
    }
    {
        let v = Ack {
            tag: U256::from(1u64),
            inner_ack: Bytes::from(vec![0xDE, 0xAD, 0xBE, 0xEF]),
        };
        out.push(vector(
            "Ack_success_with_inner",
            "Ack",
            json!({ "tag": "1", "inner_ack": "0xdeadbeef" }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // BatchAck (empty / single / three) — exercises bytes[]
    // ────────────────────────────────────────────────────────────────────
    {
        let v = BatchAck {
            acknowledgements: vec![],
        };
        out.push(vector(
            "BatchAck_empty",
            "BatchAck",
            json!({ "acknowledgements": [] }),
            &v,
        ));
    }
    {
        let v = BatchAck {
            acknowledgements: vec![Bytes::from(vec![0x01])],
        };
        out.push(vector(
            "BatchAck_single",
            "BatchAck",
            json!({ "acknowledgements": ["0x01"] }),
            &v,
        ));
    }
    {
        let v = BatchAck {
            acknowledgements: vec![
                Bytes::from(vec![0x01]),
                Bytes::from(vec![0x02, 0x03]),
                Bytes::new(),
            ],
        };
        out.push(vector(
            "BatchAck_three",
            "BatchAck",
            json!({ "acknowledgements": ["0x01", "0x0203", "0x"] }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // TokenOrderAck (FILL_TYPE_PROTOCOL / FILL_TYPE_MARKETMAKER)
    // ────────────────────────────────────────────────────────────────────
    {
        // FILL_TYPE_PROTOCOL = 0xB0CAD0
        let v = TokenOrderAck {
            fill_type: U256::from(0xB0CAD0u64),
            market_maker: Bytes::new(),
        };
        out.push(vector(
            "TokenOrderAck_protocol_fill",
            "TokenOrderAck",
            json!({
                "fill_type": "11586256",  // 0xB0CAD0 in decimal
                "market_maker": "0x",
            }),
            &v,
        ));
    }
    {
        // FILL_TYPE_MARKETMAKER = 0xD1CEC45E
        let v = TokenOrderAck {
            fill_type: U256::from(0xD1CEC45Eu64),
            market_maker: Bytes::from(b"maker-address".to_vec()),
        };
        out.push(vector(
            "TokenOrderAck_marketmaker_fill",
            "TokenOrderAck",
            json!({
                "fill_type": "3519988830",  // 0xD1CEC45E in decimal
                "market_maker": hex0x(b"maker-address"),
            }),
            &v,
        ));
    }

    // ────────────────────────────────────────────────────────────────────
    // Real-world packet from union/cosmwasm/app/ucs03-zkgm/src/msg.rs:259.
    // The hex is the `instruction` field of a `SendMsg::Send` payload caught
    // in Union's own serde test. We round-trip via alloy to confirm validity
    // and emit a decode-only fixture (no struct fields — gno just verifies
    // the decoder doesn't crash and the outer (version, opcode) matches).
    // ────────────────────────────────────────────────────────────────────
    {
        const REAL_HEX: &str = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000003e00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000012d450000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c0000000000000000000000000000000000000000000000000000000000012d450000000000000000000000000000000000000000000000000000000000000002a307832633664373366343061636535313263343330343032646362646339343839343134333035303438000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014bd1b743615f903a630393f78234b4500fbe5691a000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e62626e316e7a6e6c377372676d7478396a7565766e72617372327372736c717a7a6533303833673330773875673936663936726a7065757167386636757700000000000000000000000000000000000000000000000000000000000000000007756e6942544364000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006756e6942544300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014717dA936440d811EbBF98515EB4a8Db2443BeFf5000000000000000000000000";
        let bytes = Bytes::from_str(REAL_HEX).expect("real packet hex parses");
        let decoded = <Instruction as SolValue>::abi_decode_params(&bytes)
            .expect("real packet decodes as Instruction (params)");
        // Round-trip back. Hex equality is case-insensitive — REAL_HEX has
        // some upper-case bytes from the EVM address inside; alloy emits
        // lower-case.
        let reencoded = decoded.abi_encode_params();
        assert_eq!(
            hex0x(&reencoded),
            REAL_HEX.to_lowercase(),
            "real packet does not round-trip through alloy"
        );
        out.push(Vector {
            name: "RealPacket_msg_rs_259".to_string(),
            ty: "Instruction".to_string(),
            // Decode-only: gno test should decode and assert the outer
            // (version, opcode) sentinel without trying to construct a
            // matching nested struct from JSON.
            fields: Value::Null,
            abi_hex: REAL_HEX.to_string(),
        });
    }

    out
}

fn main() {
    let v = vectors();
    let s = serde_json::to_string_pretty(&v).expect("serialize vectors");
    println!("{}", s);
}
