name: Build and Push gnoland to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.gno-version'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: Build gnoland image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read GNO_COMMIT
        id: gno_version
        run: |
          source .gno-version
          echo "GNO_COMMIT=${GNO_COMMIT}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_REGION_V2 }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev/gno-ibc-devnet
          GNO_COMMIT: ${{ steps.gno_version.outputs.GNO_COMMIT }}
        run: |
          IMAGE_TAG=${GNO_COMMIT::7}
          docker build --no-cache \
            --build-arg GNO_COMMIT=${GNO_COMMIT} \
            -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} \
            -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest \
            .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
          echo "IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

